object Versions {
    const val kotlinVersion = "1.4.0"
    const val gradleVersion = "4.1.1"
    const val appcompatVersion = "1.1.0-rc01"
    const val daggerVersion = "2.27"
    const val lifecycleVersion = "2.2.0-alpha02"
    const val retrofitVersion = "2.9.0"
    const val okhttpVersion = "4.0.1"
    const val rxAndroidVersion = "2.1.1"
    const val rxJavaVersion = "2.2.3"
    const val glideVersion = "4.9.0"
    const val materialVersion = "1.2.0-beta01"
    const val gradleVersionPluginVersion = "0.33.0"
    const val baseQuickAdapterVersion = "3.0.4"
    const val junitVersion = "4.12"
    const val androidxTestRunnerVersion = "1.3.0-alpha01"
    const val espressoCoreVersion = "3.3.0-alpha01"
    const val truthExtVersion = "1.3.0-alpha01"
    const val mockKVersion = "1.9.3"
    const val coreTestingVersion = "2.0.0"
}